collections:
  authors:
    output: true



plugins:
  - [jekyll-paginate]



paginate: 4
paginate_path: "/posts/page:num/"

permalink: /:categories/:title/


# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter. 
    # shortname: https-lookingforspace-github-io
    shortname: rantdome


google_analytics: UA-155748596-1

twitter:
  username: Jokoisarz
  card: summary
  